specifications:
- name: Beacon
  status: revision
  spec_type: Profile
  use_cases_url:
  version: 0.2.0
- name : BioChemEntity
  status: revision
  spec_type: Type
  use_cases_url:
  version: 0.2.0
- name : Chemical
  status: revision
  spec_type: Profile
  use_cases_url:
  version: 0.1.0
- name : ChemicalStructure
  status: revision
  spec_type: Profile
  use_cases_url:
  version: 0.1.0
- name : Course
  status: revision
  spec_type: Profile
  use_cases_url:
  version: 0.1.0
- name : DataCatalog
  status: revision
  spec_type: Profile
  use_cases_url: https://docs.google.com/spreadsheets/d/1XzrZxFIuG3TS9RU8vACoUjAvaADLmI_FrIk7O3BEkxY/edit#gid=1439268036
  version: 0.2.0
- name : Dataset
  status: revision
  spec_type: Profile
  use_cases_url:
  version: 0.2.0
- name : Event
  status: revision
  spec_type: Profile
  use_cases_url:
  version: 0.1.0
- name : LabProtocol
  status: revision
  spec_type: Type
  use_cases_url: https://docs.google.com/a/ebi.ac.uk/document/d/1EZ_U2u2aJH_ERsoecaJRAJkWVHYGU2SK8HYSjvhEaMM/edit?usp=sharing
  version: 0.1.0 
- name : LabProtocol
  status: revision
  spec_type: Profile
  use_cases_url: https://docs.google.com/a/ebi.ac.uk/document/d/1EZ_U2u2aJH_ERsoecaJRAJkWVHYGU2SK8HYSjvhEaMM/edit?usp=sharing
  version: 0.1.0
#### need mapping files for metrics, organization & person
- name : Protein
  status: revision
  spec_type: Profile
  use_cases_url: https://docs.google.com/document/d/1MNU-r7CMAvKdGav1VT3XeyQXr2XwRA6JXDsoWoA0R1E
  version: 0.4.0
- name : ProteinAnnotation
  status: revision
  spec_type: Profile
  use_cases_url:
  version: 0.4.0
- name : ProteinStructure
  status: revision
  spec_type: Profile
  use_cases_url:
  version: 0.4.0
- name : DataRecord
  status: revision
  spec_type: Type
  use_cases_url: https://drive.google.com/drive/folders/0B0fE3oOZIq44U1gzLWgtV0VBaTQ
  version: 0.1.0
- name : Record
  status: revision
  spec_type: Profile
  use_cases_url: https://drive.google.com/drive/folders/0B0fE3oOZIq44U1gzLWgtV0VBaTQ
  version: 0.1.0
- name : Tool
  status: revision
  spec_type: Profile
  use_cases_url:
  version: 0.1.0
- name : TrainingMaterial
  status: revision
  spec_type: Profile
  use_cases_url:
  version: 0.2.0
