specifications:
  - name : Tool
    g_folder: Tool
    g_mapping_file: Tool mapping
    status: revision
    stereotype: none
    github_url:
    version: 0.0.1
  - name : Beacon
    g_folder: Beacon
    g_mapping_file: Beacon Mapping
    status: revision
    stereotype: none
    github_url:
    version: 0.0.1
  - name : BiologicalEntity
    g_folder: BiologicalEntity
    g_mapping_file: BiologicalEntity Mapping
    status: revision
    stereotype: none
    github_url: https://github.com/BioSchemas/BiologicalEntity
    version: 0.0.1
  - name : LaboratoryProtocol
    g_folder: LabProtocol
    g_mapping_file: LabProtocol Mapping
    status: revision
    stereotype: none
    github_url: https://github.com/BioSchemas/LaboratoryProtocol
    version: 0.0.1
  - name : Protein
    g_folder: Protein
    g_mapping_file: Protein Mapping
    status: revision
    stereotype: BiologicalEntity
    github_url: https://github.com/BioSchemas/Proteins
    version: 0.0.1
  - name : ProteinStructure
    g_folder: ProteinStructure
    g_mapping_file: ProteinStructure Mapping
    status: revision
    stereotype: BiologicalEntity
    github_url: https://github.com/BioSchemas/Proteins
    version: 0.0.1
  - name : ProteinAnnotation
    g_folder: ProteinAnnotation
    g_mapping_file: ProteinAnnotation Mapping
    status: revision
    stereotype: BiologicalEntity
    github_url: https://github.com/BioSchemas/Proteins
    version: 0.0.1